# This workflow will run all tests

name: CI

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - '**'

env:
  CODE_CLIMATE_REPORTER_ID: ${{ secrets.CODE_CLIMATE_REPORTER_ID }}
         
jobs:
  ci:
    name: Continuous Integration
    runs-on: ubuntu-latest
     
    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
        ports: ['5432:5432']
         
    steps:
      - uses: actions/checkout@v2

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0
          bundler: default
          bundler-cache: true

      - name: Standardrb Check
        run: bundle exec standardrb

      - name: Brakeman Check
        run: bundle exec brakeman

      - name: Run tests
        env:
          DATABASE_URL: postgres://postgres:password@localhost:5432/test
          RAILS_ENV: test
          PG_USER: postgres
        run: |
          bundle exec rails db:test:prepare
          bundle exec rspec gilded_rose_spec.rb 

      - name: Test & publish code coverage
        uses: paambaati/codeclimate-action@v2.7.5
        env:
          CC_TEST_REPORTER_ID: ${{ env.CODE_CLIMATE_REPORTER_ID }}
