# This workflow will run all tests

name: CI

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - '**'

jobs:
  ci:
    name: Continuous Integration
    runs-on: ubuntu-latest
         
    steps:
      - uses: actions/checkout@v2

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0
          bundler: default
          bundler-cache: true

      # - name: Standardrb Check
      #   run: bundle exec standardrb

      - name: Run tests
        run: bundle exec rspec gilded_rose_spec.rb 
