# This workflow will run all tests

name: CI

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - '**'

env:
  CODE_CLIMATE_REPORTER_ID: ${{ secrets.CODE_CLIMATE_REPORTER_ID }}
         
jobs:
  ci:
    name: Continuous Integration
    runs-on: ubuntu-latest
         
    steps:
      - uses: actions/checkout@v2

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0
          bundler: default
          bundler-cache: true

      - name: Standardrb Check
        run: bundle exec standardrb

      - name: Test & publish code coverage
        uses: paambaati/codeclimate-action@v2.7.5
        env:
          CC_TEST_REPORTER_ID: ${{ env.CODE_CLIMATE_REPORTER_ID }}
        with:
          coverageCommand: bundle exec rspec gilded_rose_spec.rb 
